<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'rainlab\\builder\\Plugin' => 'plugins\\rainlab\\builder\\Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins\\rainlab\\user\\Plugin.php',
  'RainLab\\User\\Models\\User' => 'plugins\\rainlab\\user\\models\\User.php',
  'RainLab\\User\\Models\\UserGroup' => 'plugins\\rainlab\\user\\models\\UserGroup.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins\\rainlab\\user\\classes\\UserRedirector.php',
  'RainLab\\User\\Models\\Settings' => 'plugins\\rainlab\\user\\models\\Settings.php',
  'RainLab\\Builder\\Models\\Settings' => 'plugins\\rainlab\\builder\\models\\Settings.php',
  'RainLab\\Builder\\Validation\\ReservedValidator' => 'plugins\\rainlab\\builder\\validation\\ReservedValidator.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'RainLab\\Builder\\Components\\RecordList' => 'plugins\\rainlab\\builder\\components\\RecordList.php',
  'RainLab\\Builder\\Components\\RecordDetails' => 'plugins\\rainlab\\builder\\components\\RecordDetails.php',
  'RainLab\\User\\Components\\Session' => 'plugins\\rainlab\\user\\components\\Session.php',
  'RainLab\\User\\Components\\Account' => 'plugins\\rainlab\\user\\components\\Account.php',
  'RainLab\\User\\Components\\ResetPassword' => 'plugins\\rainlab\\user\\components\\ResetPassword.php',
  'RainLab\\User\\Facades\\Auth' => 'plugins\\rainlab\\user\\facades\\Auth.php',
  'RainLab\\User\\Classes\\AuthManager' => 'plugins\\rainlab\\user\\classes\\AuthManager.php',
  'RainLab\\User\\Models\\Throttle' => 'plugins\\rainlab\\user\\models\\Throttle.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
);